name: Action

on:
  # Allow manual triggering
  workflow_dispatch:
  # Optionally run on push to main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify token validity
        run: |
          curl --location 'https://gitlab.com/api/v4/projects/71635084/packages/maven/com/t1m0/t1m0-parentpom/maven-metadata.xml' --header 'Authorization: Bearer ${{ secrets.GITLAB_TOKEN }}'

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          ./mvnw clean install -s maven-settings.xml